site_name: Practica 3
nav:
  - Home: index.md
  - About: about.md
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
docs_dir: "md"
site_dir: "docs"
extra_css: 
  - css/extra.css
plugins:
  - search
  - page-to-pdf
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details